### PR TITLE
New design for sign uo/ log in forms.

### PR DESCRIPTION
**Pull request by nikkegg**
@Porim, please check out new design, and let me know if you are okay with it. Do not merge yet, CSS needs more refactoring.
Design seems to be responsive and work well on smaller devices including Android phones. Let me know what you think.

### CODE REVIEW

**Comment by Porim** [comment]
There are some small things that need tweaking, but generally, I like it a lot. It makes the design more consistent and simpler. Also, we don't have the issue we had on Androids anymore.

Things that I think needs improving:
- Buttons seems too small on mobile phones (on both of my testing devices).
- Instead of "Go Back" button I would instead use the "Sign up" button on the login page and the "Log in" button on the signup page respectively. Then we don't need to have the following sentence at all and that makes it look cleaner(/better)  ("Don't have an account? Sign up instead.")
- It will be nicer UX if we can fit forms into the phone's screen without any scrolling. Especially now that signup forms are simplified.
- Recover password should also exclude footer if the other forms excluding it.

**Comment by nikkegg** [comment]
Thanks @Porim 
> * Buttons seems too small on mobile phones (on both of my testing devices).*
**I think this should be fixed now, as previous PR contained media queries for this**
> * Instead of "Go Back" button I would instead use the "Sign up" button on the login page and the "Log in" button on the signup page respectively. Then we don't need to have the following sentence at all and that makes it look cleaner(/better)  ("Don't have an account? Sign up instead.")*
**Agreed, will action this.**
> * It will be nicer UX if we can fit forms into the phone's screen without any scrolling. Especially now that signup forms are simplified.*
**I think once paragraph with "dont have account/have an account" is there it should rectify this**
> * Recover password should also exclude footer if the other forms excluding it.*
Y**eah, will pick this up**

**Comment by nikkegg** [comment]
@Porim - this is now finished I believe. When testing, run bundle install as I added browser gem. Code needs some refactoring as there are repititions in place, but styling is complete. Please review and merge when ready.

**Comment by Porim** [comment]
@nikkegg - there are still two issues. One that I mentioned already and it's minor, it can be resolved later on (there is unnecessary space on mobile phones that causes unnecessary scrolling). But there is one little thing that I would love to resolve before merging - the width of fields is different in login vs signup.

**Pull request merged**
