### PR TITLE
responsive logoin and sign up forms.

### PR DESCRIPTION
**Pull request by nikkegg**

### CODE REVIEW

**Comment by Porim** [comment]
The footer should be visible on the desktop without scrolling. Button in the top right corner now looks like it has no padding, but that's because footer requires scrolling on both signup and login pages. Open the login page on localhost and allsmart.uk compare them side by side, and you should see the issue. There shouldn't be a need for scrolling on large screens.
Capture

**Comment by Porim** [comment]
Navbar is broken on the login page. (iPhone 11 Pro Max)
Capture (1)

**Comment by nikkegg** [comment]
@Porim thanks for the review! Will make commit to fixing iPhone 11 max issue in a moment. Could you please let me know what is the device from the first screenshot?
I see your point with regards to scrolling, and I will try to fix this issue. However, it might be difficult to achieve, as having a visible footer might not work so well on other devices - on some of them there is white space between the footer and a form. I will run a couple of tests and let you know.

**Comment by Porim** [comment]
As mentioned in my comment, it's "the desktop". In this case viewport was 1438px by 1287px (width / height). But you should get the same issue even on much smaller viewports like your Mac and probably tablets too.
I assume that the best would be a media query based on height which will need to include navbar too (otherwise there may be white space on top of the footer).

**Pull request merged**
